import type { TravelItineraryConfig } from "@/components/travel/types";

const stops = [
  {
    day: "Day 1 🌇",
    date: "March 23",
    city: "Tokyo",
    place: "Jimbocho",
    lat: 35.6959,
    lng: 139.7577,
    zoom: 15,
    emoji: "📚",
    title: "book town!",
    description:
      "Landed at Narita after 14 hours, took the Narita Express straight to Shinjuku. Dropped bags at the hotel and made a beeline for Jimbocho — Tokyo's legendary book town, where dozens of secondhand bookshops spill their wares onto the sidewalk. Grabbed a late ramen to cap the night.",
    highlights: ["Secondhand bookshops", "Sanseido Books", "Late-night ramen"],
  },
  {
    day: "Day 2 ☀️",
    date: "March 24",
    city: "Tokyo",
    place: "Chuo",
    lat: 35.66,
    lng: 139.762,
    zoom: 16,
    emoji: "🍣",
    title: "fishy gardens",
    description:
      "Morning at Hamarikyu Gardens — a sprawling feudal-era garden right on Tokyo Bay, with tidal ponds, pine trees, and a teahouse on the water. The contrast between the green calm and the skyscrapers looming over the walls made it feel like a secret. Grabbed matcha and a wagashi sweet at the Nakajima no Ochaya teahouse.",
    highlights: ["Hamarikyu Gardens", "Nakajima no Ochaya teahouse", "Tidal duck ponds", "Views of Tokyo Bay"],
  },
  {
    day: "Day 2 🌇",
    date: "March 24",
    city: "Tokyo",
    place: "Ginza",
    lat: 35.671217,
    lng: 139.765007,
    zoom: 16,
    emoji: "🛍️",
    title: "shopping",
    description:
      "Afternoon in Ginza, Tokyo's most polished shopping district. All gleaming flagship stores, wide boulevards, and immaculate window displays. Wandered through the Itoya stationery store across six floors, then explored the Ginza Six complex and its rooftop garden.",
    highlights: ["Ginza Six", "Itoya stationery store", "Chanel, Louis Vuitton flagships", "Ginza boulevard stroll"],
  },
  {
    day: "Day 2 🌙",
    date: "March 24",
    city: "Tokyo",
    place: "Koto",
    lat: 35.6493,
    lng: 139.7897,
    zoom: 15,
    emoji: "🪐",
    title: "teamlabs",
    description:
      "Evening at teamLab Planets in Toyosu — a fully immersive digital art museum where you wade barefoot through knee-deep water that mirrors infinite koi, and lie on the floor staring up into cascading flower universes. One of those places that defies easy description. Absolutely worth the queue.",
    highlights: ["teamLab Planets", "Wading water installation", "Infinite crystal world", "Floating flower garden"],
  },
  {
    day: "Day 3 ☀️",
    date: "March 25",
    city: "Tokyo",
    place: "Shinjuku",
    lat: 35.6938,
    lng: 139.7034,
    zoom: 15,
    emoji: "🎋",
    title: "our name",
    description:
      "Morning pilgrimage to the Suga Shrine — famous as the real-world location from Your Name (Kimi no Na wa). Climbed the steps and tried to feel the Makoto Shinkai magic. Then strolled through Shinjuku Gyoen, one of Tokyo's finest parks, where early cherry blossoms were just beginning to open.",
    highlights: ["Suga Shrine (Your Name steps)", "Shinjuku Gyoen National Garden", "Early sakura blossoms", "French garden section"],
  },
  {
    day: "Day 3 🌙",
    date: "March 25",
    city: "Tokyo",
    place: "Mitaka",
    lat: 35.6962,
    lng: 139.5703,
    zoom: 16,
    emoji: "🍃",
    title: "ghibli",
    description:
      "Trekked out west to Mitaka for the Ghibli Museum — tickets booked months in advance, and worth every second of the wait. The museum is exactly as whimsical and handcrafted as you'd hope, with original animation cels, hand-drawn storyboards, the rooftop Laputa robot, and an exclusive short film shown only here. Pure inner-child joy.",
    highlights: ["Ghibli Museum", "Rooftop Laputa robot", "Exclusive short film", "Cat Bus room", "Mitaka forest walk"],
  },
  {
    day: "Day 3 🌙",
    date: "March 25",
    city: "Tokyo",
    place: "Koenji",
    lat: 35.7056,
    lng: 139.6496,
    zoom: 16,
    emoji: "🎸",
    title: "koenji",
    description:
      "Stopped off in Koenji on the way back — a neighbourhood with a totally different vibe from the rest of Tokyo. Vintage clothing shops, record stores, and the famous Koenji Pure Love Shopping Street (Junjou Shotengai). Grabbed drinks at a jazz bar and browsed secondhand vinyl.",
    highlights: ["Pure Love Shopping Street (Junjou Shotengai)", "Vintage clothing stores", "Secondhand record shops", "Jazz bars"],
  },
  {
    day: "Day 4 ☀️",
    date: "March 26",
    city: "Kamakura",
    place: "Kanagawa",
    lat: 35.3192,
    lng: 139.5468,
    zoom: 16,
    emoji: "🌊",
    title: "sea day trip",
    description:
      "Day trip to Kamakura, the ancient seat of Japan's first shogunate. Hiked the Daibutsu trail through bamboo groves to reach the Great Buddha — a 13-metre bronze giant sitting serenely outdoors for 700 years. Walked down to Yuigahama Beach for a wind-swept stroll along Sagami Bay with views of Mt Fuji just visible on the horizon.",
    highlights: ["Great Buddha (Kotoku-in)", "Daibutsu hiking trail", "Bamboo grove path", "Yuigahama Beach", "Hase-dera temple"],
  },
  {
    day: "Day 5 🌙",
    date: "March 27",
    city: "Tokyo",
    place: "Akihabara",
    lat: 35.6984,
    lng: 139.773,
    zoom: 16,
    emoji: "⚡",
    title: "electric town",
    description:
      "Akihabara — Electric Town. Multi-storey arcades, walls of retro game cartridges, anime figures behind glass, and maid cafés on every floor. Whether or not this is your world, the sheer density of it is a spectacle. Spent way too long in the retro game floors of Super Potato.",
    highlights: ["Super Potato retro games", "Yodobashi Camera", "Arcades and crane games", "Akihabara street stalls"],
  },
  {
    day: "Day 5 🌙",
    date: "March 27",
    city: "Tokyo",
    place: "Shinjuku",
    lat: 35.6896,
    lng: 139.6917,
    zoom: 16,
    emoji: "🌆",
    title: "city sightseeing",
    description:
      "Headed to the Tokyo Metropolitan Government Building in west Shinjuku for the free observation deck — sweeping 360° views across the entire city, and on a clear day, Mt Fuji in the distance. The twin towers are an architectural statement in themselves. No ticket, no queue, no excuse not to go.",
    highlights: ["Tokyo Metropolitan Government Building observatory", "Mt Fuji views on clear days", "West Shinjuku skyscraper district", "Free entry"],
  },
  {
    day: "Day 5 🌙",
    date: "March 27",
    city: "Tokyo",
    place: "Harajuku",
    lat: 35.6702,
    lng: 139.7027,
    zoom: 16,
    emoji: "🌃",
    title: "nightlife",
    description:
      "Evening in Harajuku and the backstreets of Ura-Harajuku. By night the area trades the Takeshita Street tourist bustle for intimate cocktail bars, hidden izakayas, and low-lit live music venues tucked into the Cat Street side streets. Found a tiny standing bar with excellent natural wine.",
    highlights: ["Cat Street bars", "Ura-Harajuku side streets", "Izakayas", "Standing cocktail bars"],
  },
  {
    day: "Day 5 🌙",
    date: "March 27",
    city: "Tokyo",
    place: "Meguro",
    lat: 35.6446,
    lng: 139.6993,
    zoom: 16,
    emoji: "🌸",
    title: "sakura stroll",
    description:
      "The Meguro River at cherry blossom time is one of Tokyo's great sights — a tunnel of sakura branches arching over the water, petals drifting down into the canal below. Food and drink stalls line the banks. Picked up a canned beer and joined the slow river of people drifting beneath the blossoms.",
    highlights: ["Cherry blossom tunnel over Meguro River", "Sakura festival stalls", "Nakameguro canal walk", "Lantern-lit evenings"],
  },
  {
    day: "Day 6 🌙",
    date: "March 28",
    city: "Itō",
    place: "Izu",
    lat: 34.9769,
    lng: 138.9468,
    zoom: 16,
    emoji: "♨️",
    title: "onsen getaway",
    description:
      "Escaped the city for a night in Izu Peninsula — Japan's classic onsen retreat, a couple of hours south of Tokyo by train. Checked into a ryokan, changed into a yukata, and spent the evening between the rotenburo outdoor hot spring and a multi-course kaiseki dinner. The kind of reset that makes you feel human again.",
    highlights: ["Rotenburo outdoor onsen", "Ryokan stay", "Kaiseki multi-course dinner", "Izu Peninsula scenery", "Yukata and geta"],
  },
  {
    day: "Day 7 ☀️",
    date: "March 29",
    city: "Kyoto",
    place: "Shimogyo Ward",
    lat: 34.9977,
    lng: 135.7547,
    zoom: 16,
    emoji: "🍢",
    title: "kyotoooo",
    description:
      "Shinkansen from Mishima to Kyoto. Arrived at Colours Guesthouse in Shimogyo — a lively, well-run hostel in the heart of the old city, right near Nishiki Market. Dropped bags, grabbed a paper map, and wandered Nishiki's narrow covered arcade for an evening snack crawl: grilled skewers, dashimaki tamago, pickles.",
    highlights: ["Colours Guesthouse", "Nishiki Market", "Tamagoyaki skewers", "Evening food stall crawl", "Kyoto arrival"],
  },
  {
    day: "Day 8 🌙",
    date: "March 30",
    city: "Kyoto",
    place: "Sakyo Ward",
    lat: 35.0369,
    lng: 135.7801,
    zoom: 16,
    emoji: "🗿",
    title: "philosopher's path",
    description:
      "A full day in northeast Kyoto. Walked the Philosopher's Path — a canal-side stone walkway lined with cherry trees — from Ginkaku-ji down toward Nanzen-ji. Then took the bus south to Fushimi Inari, arriving in the late afternoon when the tourist crowds thin and the endless tunnels of vermilion torii gates glow in the slanted light.",
    highlights: ["Philosopher's Path", "Ginkaku-ji (Silver Pavilion)", "Nanzen-ji aqueduct", "Fushimi Inari torii gates", "Summit hike at dusk"],
  },
  {
    day: "Day 9 🌙",
    date: "March 31",
    city: "Nara",
    place: "Nara Park",
    lat: 34.6851,
    lng: 135.843,
    zoom: 16,
    emoji: "🦌",
    title: "deer",
    description:
      "Day trip to Nara — home to over a thousand wild sika deer who roam freely through the park and bow for crackers. Visited Todai-ji, housing the enormous Great Buddha hall, and wandered the lantern-lined paths of Kasuga Taisha shrine deep in the cedar forest. The deer are absolutely unhinged and we loved every second of it.",
    highlights: ["Nara sika deer", "Todai-ji Great Buddha hall", "Kasuga Taisha shrine", "Deer cracker vendors", "Nara Park stroll"],
  },
  {
    day: "Day 9 🌙",
    date: "March 31",
    city: "Kyoto",
    place: "Uji",
    lat: 34.8904,
    lng: 135.8032,
    zoom: 16,
    emoji: "🍵",
    title: "matcha village",
    description:
      "Stopped in Uji on the way back to Kyoto — Japan's matcha heartland. The town sits along the Uji River and the air practically smells green. Tried matcha soft serve, proper tencha ice cream, and sat in the garden of Byodoin temple, a 10th-century hall so beautiful it appears on the 10-yen coin.",
    highlights: ["Byodoin temple (10-yen coin)", "Matcha soft serve", "Uji River promenade", "Uji Bridge", "Matcha tea shops"],
  },
  {
    day: "Day 10 🌙",
    date: "April 1",
    city: "Tokyo",
    place: "Ginza",
    lat: 35.681236,
    lng: 139.767125,
    zoom: 16,
    emoji: "✈️",
    title: "last day",
    description:
      "Back to Tokyo for the final day. Returned to Ginza with no agenda — just slow coffee, a last look at the city, and the particular bittersweetness of a trip ending. Picked up omiyage at the depachika basement food halls, repacked everything that wouldn't fit, and headed to Narita with a bag full of books, ceramics, and snacks.",
    highlights: ["Depachika souvenir shopping", "Final Tokyo coffee", "Ginza department stores", "Narita Express farewell"],
  },
];

export const japanTrip = {
  id: "japan-2025",
  title: "Japan",
  nativeTitle: "日本",
  dates: "March 23 - April 2, 2025",
  intro: "spin the clock through each day, afternoon, and night.",
  // heroCharacter: "旅",
  accentColor: "#c0392b",
  stops,
  afterRoute: {
    eyebrow: "After The Route",
    title: "Food, Reflection, and Favorites",
    description: "The map tells the route, but these are the moments that lingered after the trip: the meals, the small surprises, and what I would do differently next time.",
    cards: [
      {
        eyebrow: "Food",
        title: "Best Things I Ate",
        description: "Midnight ramen in Shinjuku, smoky yakitori in Omoide Yokocho, and the surprisingly delicate kaiseki dinner in Kyoto.",
      },
      {
        eyebrow: "Reflection",
        title: "What Stayed With Me",
        description: "The rhythm of early mornings, long walks, and tiny neighborhood details made the trip feel calm even on busy days.",
      },
      {
        eyebrow: "Favorites",
        title: "Top Moments",
        description: "Dawn in Arashiyama, the first blossom along Shirakawa Canal, and watching Shibuya Crossing from above before joining the crowd.",
      },
      {
        eyebrow: "Next Time",
        title: "What I'd Change",
        description: "I would add one slower day between city transfers and book a countryside onsen stay to balance the city pace.",
      },
    ],
  },
} satisfies TravelItineraryConfig;
